# Generated by Django 4.1.4 on 2024-01-31 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_technology_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pro_git',
            field=models.URLField(default='url'),
            preserve_default=False,
        ),
    ]
